
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: drag-drop-practice_development

test:
  <<: *default
  database: drag-drop-practice_test

production:
  <<: *default
  database: drag-drop-practice_production
  username: drag-drop-practice
  password: <%= ENV['ADDING-REACT-TO-RAILS_DATABASE_PASSWORD'] %>
